
"""RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UFm8QKmSZselowhZpcit573rbGvHQT1V

##RNN
RNN is a type of deep learning neural network specially designed for sequential data or time-series data where previous information is important. Unlike traditional neural networks, RNN has a memory mechanism. It remembers previous inputs and uses that information for predicting the next output.
#Working of RNN
In RNN, the output from the previous step is fed again into the network along with the current input.
Example:

“I love deep learning”

###Step 1: Read I
###Step 2: Remember I and read love
###Step 3: Remember I love and read deep
###Step 4: Continue similarly

So, previous context helps in understanding current data.

#Architecture of RNN

Input → Hidden State → Output

  ^

  |

pravious state


The hidden state acts like memory.
Previous state information is passed to the next step.
| Feature               | Traditional NN (ANN)             | RNN                              |
| --------------------- | -------------------------------- | -------------------------------- |
| Data Type             | Works on normal independent data | Works on sequential data         |
| Memory                | No memory                        | Has memory                       |
| Previous Information  | Not used                         | Used                             |
| Input Processing      | All inputs independent           | Inputs processed sequentially    |
| Best For              | Classification and regression    | NLP, speech, sequence prediction |
| Connection Type       | Feedforward only                 | Feedback / recurrent connections |
| Context Understanding | Poor                             | Better                           |


#Important Key Points of RNN
RNN is good for sequence learning.
It uses hidden states for memory.
Same weights are used at every time step.
It can process variable-length sequences.
Training is done using Backpropagation Through Time (BPTT).
#Problems in Basic RNN
###1) Vanishing Gradient Problem
During backpropagation, gradients become extremely small, so the model cannot learn long-term dependencies.
###2) Exploding Gradient Problem
Gradients become too large, causing unstable training. Because of this, RNN struggles with long sequences.
#Disadvantages of RNN
*Slow training

*Vanishing gradient problem

*Difficult to train on long sequences

*Less parallelization
"""

import tens

from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense, LSTM, GRU, Bidirectional
import numpy as np

#Getting reviews with words that come under 5000
#most occurring words in the entire
#corpus of textual review data
vocab_size = 5000
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=vocab_size)

print(x_train[0])

#getting all the words from world_index dictionary
word_idx = imdb.get_word_index()
#originally the index number of a value and not a key
#hence converting the index as key and the words as values
word_idx = {i: word for word, i in word_idx.items()}
#again printing the review
print([word_idx[i] for i in x_train[0]])

#get the minimum and the maximum length of reviews
print("Maximum review length: ", len(max((x_train+x_test), key=len)))
print("Minimum review length: ", len(min((x_train+x_test), key=len)))

from tensorflow.keras.preprocessing import sequence

#keeping a fixed length of all reviews to max 400 words
max_words = 400
x_train = sequence.pad_sequences(x_train, maxlen=max_words)
x_test = sequence.pad_sequences(x_test, maxlen=max_words)
x_valid, y_valid = x_train[:64], y_train[:64]
x_train, y_train = x_train[64:], y_train[64:]

#fixing every word's embedding size to be 32
embd_len = 32

# creating a RNN model
RNN_model = Sequential(name ="Simple_RNN")
RNN_model.add(Embedding(vocab_size,
                        embd_len,
                        input_length=max_words))
#In case of a stacked (more than one layer of RNN)
#use return_sequences=True
RNN_model.add(SimpleRNN(128,
                        activation='tanh',
                        return_sequences=False))
RNN_model.add(Dense(1, activation='sigmoid'))

#printing model summary
print(RNN_model.summary())

#compile model
RNN_model.compile(loss="binary_crossentropy",
                  optimizer='adam',
                  metrics=['accuracy']
                  )

#training the model
history = RNN_model.fit(x_train,
                      y_train,
                      batch_size=64,
                      epochs=5,
                      verbose=1,
                      validation_data=(x_valid, y_valid))
#printing model score on test data
print()
print("Simple_RNN score--->", RNN_model.evaluate(x_test, y_test, verbose=0))

